### PR TITLE
MultiBzDecoder: Fix Read trait bound

### PR DESCRIPTION
**Pull request by Philpax**
The implementation of `read::MultiBzDecoder` requires the use of the `Read` trait, but this was not enforced, leading to compile-time errors when used against Rust 1.32.0.

This PR removes the separate `impl` block for `MultiBzDecoder` so that the remaining implementation methods fall under the `Read` impl block.

(n.b. I realised this wasn't an issue after updating to 1.36.0, but I'd already fixed it, so I figured I might as well submit it)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! The current iteration though I think is correct in that the accessors shouldn't require extra `Read` bounds, so perhaps this PR isn't necessary?

**Comment by Philpax** [comment]
Yeah, the current iteration compiles fine under 1.36.0, but fails under 1.32.0:
```
error[E0599]: no method named `get_ref` found for type `&std::io::BufReader<R>` in the current scope
   --> src/read.rs:191:30
    |
191 |         self.inner.get_ref().get_ref()
    |                              ^^^^^^^
    |
    = note: the method `get_ref` exists but the following trait bounds were not satisfied:
            `R : std::io::Read`
            `R : std::io::Read`

error[E0599]: no method named `get_mut` found for type `&mut std::io::BufReader<R>` in the current scope
   --> src/read.rs:199:30
    |
199 |         self.inner.get_mut().get_mut()
    |                              ^^^^^^^
    |
    = note: the method `get_mut` exists but the following trait bounds were not satisfied:
            `R : std::io::Read`
            `R : std::io::Read`

error[E0599]: no method named `into_inner` found for type `std::io::BufReader<R>` in the current scope
   --> src/read.rs:204:33
    |
204 |         self.inner.into_inner().into_inner()
    |                                 ^^^^^^^^^^
    |
    = note: the method `into_inner` exists but the following trait bounds were not satisfied:
            `R : std::io::Read`
```
This is probably an edge case (I only noticed because I'd forgotten to update my rustc), but it might be better to be explicit about it? The `BzDecoder` implementation uses `Read`, for reference.

**Comment by alexcrichton** [comment]
Ah ok I think that's fine, just means that the crate requires 1.36 now!
